name: CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn test --ci --coverage --maxWorkers=2
            - run: yarn build
            - uses: actions/upload-artifact@v2
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
