name: npm Publish dev

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  # More info: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
                  registry-url: 'https://registry.npmjs.org'
            - name: Use node_modules cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: yarn-node-16-lock-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      yarn-node-16-lock-
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - uses: actions/upload-artifact@v3
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
            - run: yarn size
            - uses: martinbeentjes/npm-get-version-action@v1.3.1
              id: package-version
            - run: yarn version --no-git-tag-version --new-version ${{ steps.package-version.outputs.current-version }}-dev.${{ github.sha }}
              # npm install -g npm@latest is necessary to make provenance available. More info: https://docs.npmjs.com/generating-provenance-statements
            - run: npm install -g npm@latest
            - run: npm publish --access public --tag dev
              env:
                  # Is connected with actions/setup-node -> registry-url
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
