name: npm publish

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Use node_modules cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: yarn-node-16-lock-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      yarn-node-16-lock-
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn test --ci --coverage --maxWorkers=2
            - run: yarn build
            - uses: actions/upload-artifact@v3
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
            - run: yarn test:exports
            - run: yarn size
              # npm install -g npm@latest is necessary to make provenance available. More info: https://docs.npmjs.com/generating-provenance-statements
            - run: npm install -g npm@latest
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
